### ISSUE TITLE
New schema inference doesn't work with parallelism

### ISSUE THREAD

**Issue by CoderJoshDK** [mongodb-labs/mongo-arrow#390]
#383 changes the schema building logic to promote int32 to int64. But if different threads/workers (introduced in #384) evaluate different schemas, the error persists:

```
ArrowTypeError: Unable to merge: Field timespan has incompatible types: int32 vs int64
```

#371 is related. That used to be an error I was getting but after building off of main, it went away. Turning on parallelism reintroduced it (a new version of the same error). 

At the time of writing, I don't have a minimal example.  <sub>If I manage to create one // if you specifically request one, I can try</sub>

As you can see in the following snippet

https://github.com/mongodb-labs/mongo-arrow/blob/006f0e572f8945547a19254f649b9b1b76e9c863/bindings/python/pymongoarrow/api.py#L169-L177

The fix is likely to change `promote_options="default"` to `promote_options=”permissive”,`

> If promote_options=”permissive”, the behavior of default plus types will be promoted to the common denominator that fits all the fields.

Or if you wanted to be a bit more conservative:

```diff
- return pa.concat_tables(results, promote_options="default") 
+ return pa.concat_tables(results, promote_options="default" if allow_invalid else "permissive")
```

I have not confirmed if this change would fix my bug. Will try to do that sometime soon.
If I can confirm that this is a fix, I can open a PR

<details><summary>permissive?</summary>
<p>

my bias is to always provide `permissive` instead of based on `allow_invalid`. Mainly because any schema specific errors that would be raised by `allow_invalid` should be handled already in the processing and `permissive` should only pick up these schema drifts between workers. 

</p>
</details>
