### PR TITLE
fix: parallel arrow with differing schema

### LINKED ISSUE #390: New schema inference doesn't work with parallelism
#383 changes the schema building logic to promote int32 to int64. But if different threads/workers (introduced in #384) evaluate different schemas, the error persists:

```
ArrowTypeError: Unable to merge: Field timespan has incompatible types: int32 vs int64
```

#371 is related. That used to be an error I was getting but after building off of main, it went away. Turning on parallelism reintroduced it (a new version of the same error). 

At the time of writing, I don't have a minimal example.  <sub>If I manage to create one // if you specifically request one, I can try</sub>

As you can see in the following snippet

https://github.com/mongodb-labs/mongo-arrow/blob/006f0e572f8945547a19254f649b9b1b76e9c863/bindings/python/pymongoarrow/api.py#L169-L177

The fix is likely to change `promote_options="default"` to `promote_options=”permissive”,`

> If promote_options=”permissive”, the behavior of default plus types will be promoted to the common denominator that fits all the fields.

Or if you wanted to be a bit more conservative:

```diff
- return pa.concat_tables(results, promote_options="default") 
+ return pa.concat_tables(results, promote_options="default" if allow_invalid else "permissive")
```

I have not confirmed if this change would fix my bug. Will try to do that sometime soon.
If I can confirm that this is a fix, I can open a PR

<details><summary>permissive?</summary>
<p>

my bias is to always provide `permissive` instead of based on `allow_invalid`. Mainly because any schema specific errors that would be raised by `allow_invalid` should be handled already in the processing and `permissive` should only pick up these schema drifts between workers. 

</p>
</details>

### PR DESCRIPTION
**Pull request by CoderJoshDK**
## Changes in this PR

#384 introduces "parallel batch processing for PyMongoArrow" and #383 handles a case where the inferred schema should be promoted to Int64 (if previously Int32). However, they did not work together on the edge case where not all batches were promoted.

While I was creating this PR, I found a bug where no parallelism was ditching existing values:

<details><summary>Error</summary>
<p>

```
>       self.assertTrue(
            table_off.equals(table_proc),
            msg=f"tables differ:\n{table_off}\n\n{table_proc}",
        )
E       AssertionError: False is not true : tables differ:
E       pyarrow.Table
E       _id: int32
E       value: int64
E       ----
E       _id: [[0,1,2,3,4,...,46,47,48,49,50]]
E       value: [[null,null,null,null,null,...,null,null,null,null,1099511627776]]
E
E       pyarrow.Table
E       _id: int32
E       value: int64
E       ----
E       _id: [[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19],...,[40,41,42,43,44,45,46,47,48,49],[50]]
E       value: [[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19],...,[40,41,42,43,44,45,46,47,48,49],[1099511627776]]

test/test_arrow.py:1467: AssertionError
```

</p>
</details>

This was because the builder was being filled with values and then a new one was constructed, replacing all values.

This closes #390  

## Test Plan

I tested this in two ways. I added the unit tests and I ran this against a real cluster I was having issues with.

### Checklist for Author
- [x] Did you update the changelog (if necessary)?
 		I did not update the changelog because this fix still fits inside all the new changes
- [x] Is there test coverage?
- [ ] Is any followup work tracked in a JIRA ticket? If so, add link(s).

### Checklist for Reviewer
- [ ] Does the title of the PR reference a JIRA Ticket?
- [ ] Do you fully understand the implementation? (Would you be comfortable explaining how this code works to someone else?)
- [ ] Is all relevant documentation (README or docstring) updated?

### CODE REVIEW

File: bindings/python/pymongoarrow/lib.pyx [hunk 1]
```diff
@@ -244,7 +244,12 @@ cdef class BuilderManager:
             builder = <_ArrayBuilderBase>self.builder_map.get(full_key, None)
             # If the inferred type was int32 but the same field has an int64 value,
             # re-infer the field's type since int32 is a strict subset of int64.
-            if not self.has_schema and (builder is None or builder.type_marker == BSON_TYPE_INT32 and value_t == BSON_TYPE_INT64):
+            # If builder already existed, avoid ditching previously appended values.
+            if not self.has_schema and builder is not None and builder.type_marker == BSON_TYPE_INT32 and value_t == BSON_TYPE_INT64:
+                old_array = builder.finish().cast('int64')
+                builder = self.get_builder(full_key, value_t, doc_iter, True)
+                builder.append_values(old_array.to_pylist())
```
[the remark this answers is not in the document]
Comment (CoderJoshDK) [reply bindings/python/pymongoarrow/lib.pyx]: Should be resolved now.

**Review by caseyclements — CHANGES_REQUESTED** [review]
Hi @CoderJoshDK 

Thanks for identifying and fixing this bug! In order to merge this, we simply need to fix the tests.

   The problem you encountered: When you tried to iterate directly over a PyArrow array with for val in old_array:, you got TypeError: an integer is
   required because:

     1. Iterating over a PyArrow array yields Int64Scalar objects, not Python integers
     2. The C++ Append() method expects a C int64_t type, not a Python object
     3. Cython can't automatically convert Int64Scalar to int64_t

   The fix: Use .to_numpy() to get a numpy array, which Cython can efficiently convert to C types:

   values_np = old_array.to_numpy(zero_copy_only=False)
   for i in range(n_vals):
       (<Int64Builder>builder).builder.get().Append(values_np[i])

   This approach:
     • ✅ Avoids the BSON encode/decode overhead from the original PR
     • ✅ Uses efficient numpy → C conversion
     • ✅ Is zero-copy when there are no nulls
     • ✅ Adds only ~34-62% overhead compared to no promotion at all

**Comment by caseyclements** [comment]
I've created [INTPYTHON-933](https://jira.mongodb.org/browse/INTPYTHON-933) to track this. I've also got a proposed fix too, but I have to run for the day.!

**Comment by CoderJoshDK** [comment]
Hey, thanks for getting on this quickly! I am a bit confused by your comment. For now, I have a simple patch where I cast val with `to_py()`. 
Casting to numpy still seems to require the builder completion and then evaluating for a null (NaN?) value. 
To make sure that the overflow logic also captures `None` well, I added a new row to the test(s).

The main thing that I can see being more efficient is skipping `builder.finish()` but I am unsure of a way to do this.

Either way, I look forward to your review and insight!

**Comment by CoderJoshDK** [comment]
Ok this lint failure was related to #393 hahaha, but glad to see everything else pass.
(My local version of ruff is up to date compared to this branch and I forgot to ignore the other auto format changes.)

Sorry for the sloppyness of some of these details!

**Review by caseyclements — APPROVED** [review]
This looks great now @CoderJoshDK . The change you made sidesteps the bson N round-trip issue of the original submission, so we're all set!

**Comment by caseyclements** [comment]
Hi @CoderJoshDK . I've just released this as part of v1.13.0. Thanks again for your contribution!
